baseURL = "https://softweb-fr.github.io/website/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Softweb"
theme = "cayman-hugo-theme"

# Google analytics
googleAnalytics = "UA-43088213-1"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[params]
project_name = "Softweb.fr"
project_tagline = "Don't touch my closure!"
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme)."
