baseURL = "https://softweb.fr/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Softweb"
theme = "cayman-hugo-theme"

# Google analytics
googleAnalytics = "UA-43088213-1"

# Disqus comments
disqusShortname = "softweb-fr"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  project_name = "SOFTWEB.FR"
  project_tagline = "Don't touch my closure!"

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  footer = "Sources on [Github](https://github.com/softweb-fr/softweb-fr.github.io). Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme)."

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 3
