baseURL = "https://softweb.fr/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Softweb"
theme = "gokarna"
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "monokai"
pygmentsCodefences = true

[params]
  description = "Don't touch my closure!"
  footer = "Sources on [Github](https://github.com/softweb-fr/softweb-fr.github.io). Made with [Hugo](https://gohugo.io/). Themed by [Gokarna](https://github.com/526avijitgupta/gokarna)."
  showBackToTopButton = true
  showPostNavLinks = true

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Blog"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/softweb-fr/softweb-fr.github.io"
    weight = 3

  [[menu.main]]
    name = "RSS"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 4
